idf_component_register(
    SRCS
        "cmds.c"
        "cmd_env.c"
        "cmd_fs.c"
        "cmd_sys.c"
        "cmd_run.c"
        "cmd_net.c"
        "cmd_motd.c"
        "cmd_time.c"
        "cmd_blk.c"
        "cmd_usbhost.c"
        "cmd_ota.c"
        "cmd_hash.c"
        "cmd_bt.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "priv_include"
    REQUIRES
        esp_common
    PRIV_REQUIRES
        espix_kernel
        espix_fs
        espix_proc
        espix_shell
        espix_fault
        espix_net
        espix_bt
        espix_usb
        espix_auth
        espix_time
        espix_ota
        app_update
        mbedtls
        esp_blockdev
        lwip
        freertos
        esp_system
        esp_timer
        heap
        spi_flash
)
