idf_component_register(
    SRCS
        "history.c"
        "registry.c"
        "session.c"
        "tty_console.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        esp_common
        espix_kernel
        espressif__esp_linenoise
    PRIV_REQUIRES
        console
        esp_timer
        espix_fs
        freertos
        vfs
        esp_driver_uart
        esp_driver_usb_serial_jtag
)
