idf_component_register(
    SRCS
        "fs.c"
        "mode.c"
        "vfs.c"
        "access.c"
        "dev.c"
        "fat.c"
        "part.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "priv_include"
    REQUIRES
        esp_common
        esp_blockdev
    PRIV_REQUIRES
        esp_partition
        fatfs
        espix_kernel
        espix_proc
        espix_shell
        joltwallet__littlefs
        vfs
)
