idf_component_register(
    SRCS
        "display.c"
        "rfb.c"
        "vnc_des.c"
        "font8x8.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "priv_include"
    PRIV_REQUIRES
        espix_kernel
        freertos
        lwip
        heap
        esp_timer
        esp_hw_support
        esp_system
)
