idf_component_register(
    SRCS
        "proc.c"
        "exec.c"
        "abi_cxx.cpp"
        "abi_drivers.c"
        "abi_fs.c"
        "abi_signal.c"
        "abi_time.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "priv_include"
    REQUIRES
        esp_common
        freertos
        espix_kernel
    PRIV_REQUIRES
        espix_fs
        espix_shell
        espressif__elf_loader
        esp_timer
        heap
        esp_driver_rmt
        esp_driver_gpio
        soc
)
