#!/usr/bin/env python3
"""Emit a C header holding byte arrays for one or more binary files.

    tools/emit-array.py <out.h> <name> <file> [<name> <file> ...]

Used for the partition tables the loader carries: generating them from the same
CSVs the project builds with keeps one source of truth, and a byte array needs no
partition-table format knowledge at run time.
"""
import sys


def main():
    if len(sys.argv) < 4 or (len(sys.argv) - 2) % 2 != 0:
        sys.stderr.write(__doc__)
        return 2

    out = sys.argv[1]
    pairs = [(sys.argv[i], sys.argv[i + 1]) for i in range(2, len(sys.argv), 2)]

    with open(out, "w") as h:
        h.write("/* Generated by tools/emit-array.py -- do not edit. */\n")
        h.write("#pragma once\n\n")
        for name, path in pairs:
            with open(path, "rb") as f:
                data = f.read()
            h.write("static const unsigned char %s[] = {" % name)
            for i, b in enumerate(data):
                if i % 12 == 0:
                    h.write("\n    ")
                h.write("0x%02x, " % b)
            h.write("\n};\n")
            h.write("static const unsigned int %s_len = %uu;\n\n" % (name, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
