idf_component_register(
    SRCS
        "ssh_server.c"
        "ssh_transport.c"
        "ssh_hostkey.c"
        "ssh_kex.c"
        "ssh_auth.c"
        "ssh_channel.c"
    INCLUDE_DIRS
        "include"
    PRIV_INCLUDE_DIRS
        "priv_include"
    REQUIRES
        esp_common
    PRIV_REQUIRES
        espix_kernel
        espix_auth
        espix_shell
        espressif__esp_linenoise
        espix_proc
        espix_fs
        lwip
        mbedtls
        esp_hw_support
        freertos
)
